[versions]
activityCompose = "1.10.1"
agp = "8.8.2"
appUpdateKtx = "2.1.0"
chartboostSdk = "9.8.1"
compose = "1.0.0-beta01"
converterMoshi = "2.6.2"
coreKtx = "1.16.0"
desugar_jdk_libs = "2.1.5"
engageCore = "1.5.8"
espressoCore = "3.6.1"
facebook = "6.20.0.0"
firebaseBom = "33.16.0"
firebaseMessaging = "24.1.2"
junit = "4.13.2"
junitVersion = "1.2.1"
koinAndroidxCompose = "4.0.2"
kotlin = "2.0.21"
gs = "4.4.3"
crash = "3.0.4"
compose2 = "2.0.0"
lifecycleRuntimeKtx = "2.9.1"
material3 = "1.3.2"
materialIconsExtended = "1.7.8"
mockitoCore = "5.2.0"
navigationCompose = "2.9.0"
okhttp = "5.0.0-alpha.2"
okhttpVersion = "4.12.0"
playServicesAds = "24.4.0"
playServicesAdsIdentifier = "18.2.0"
playServicesBase = "18.7.0"
preferenceKtx = "1.2.1"
retrofit = "2.9.0"
reviewKtx = "2.0.2"
roomRuntime = "2.7.2"
uiTestManifest = "1.8.3"
unity = "4.15.0"
unityAds = "4.15.0.0"
userMessagingPlatform = "3.2.0"
vungleAds = "7.5.0"
ksp = "2.0.21-1.0.27"
landscapistGlide = "2.4.9"
[libraries]
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdateKtx" }
chartboost-sdk = { module = "com.chartboost:chartboost-sdk", version.ref = "chartboostSdk" }
compose = { module = "com.github.bumptech.glide:compose", version.ref = "compose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
engage-core = { module = "com.google.android.engage:engage-core", version.ref = "engageCore" }
facebook = { module = "com.google.ads.mediation:facebook", version.ref = "facebook" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-v4120 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unity" }
unity-mediation = {module ="com.google.ads.mediation:unity", version.ref = "unityAds"}
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }
vungle-ads = { module = "com.vungle:vungle-ads", version.ref = "vungleAds" }

landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapistGlide" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gs" }
crash-analytics = { id = "com.google.firebase.crashlytics", version.ref = "crash" }
android-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose2" }
android-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

